name: CI-CD-Pipeline-to-AWS 
env:
  EB_PACKEGE_S3_BUCKET_NAME : "application-packege"
  EB_APPLICATION_NAME       : "gatsby-starter"
  EB_ENVIROMENT_NAME        : "gatsby.env"
  DEPPLOY_PACKAGE_NAME      : "gatsby_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-1"
 
on:
  push:
    branches: 
      - master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
     - name: Git clone our repo
       uses: actions/checkout@v1
       
     - name: Create ZIP deployment package
       run: zip -r ${{ env.DEPPLOY_PACKAGE_NAME }} ./ -x *.git*
       
     - name: Configure my AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-eccess-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region           : ${{ env.AWS_REGION_NAME }}

     - name: Copy Deployment packege to S3 bucket
       run: aws_s3_cp ${{ env.DEPPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/

     - name: Print Happy Massage for CI finish
       run: echo «CI Pipeline part Finished successfully!»      
      
