name: CI-CD-Pipeline-to-AWS 
env:
  EB_PACKEGE_S3_BUCKET_NAME : "s3-bucket-app-files"
  EB_APPLICATION_NAME       : "gatsby-starter"
  EB_ENVIROMENT_NAME        : "gatsby.env"
  DEPLOY_PACKAGE_NAME       : "gatsby_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-1"
 
on:
  push:
    branches: 
      - master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
     - name: Git clone our repo
       uses: actions/checkout@v1
       
     - name: Create ZIP deployment package
       run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
       
     - name: Configure my AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region           : ${{ env.AWS_REGION_NAME }}

     - name: Copy Deployment packege to S3 bucket
       run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKEGE_S3_BUCKET_NAME }}

     - name: Print Happy Massage for CI finish
       run: echo "CI Pipeline part Finished successfully!"
       
  my_cd_part:
    runs-on: ubuntu-latest
    needs: [my_ci_part]
    
    steps:
     - name: Configure my AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region           : ${{ env.AWS_REGION_NAME }}
          
     - name: Crate new gatsby Application
       run: |
          aws elasticbeanstalk create-application-version 
          --application-name ${{ env.EB_APPLICATION_NAME }}
          --source-bundle S3Bucket="${{ env.EB_PACKEGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPPLOY_PACKAGE_NAME }}"
          --version-label "Ver=${{ github.sha }}"
          --description "CommitSHA=${{ github.sha }}"

     - name: Deploy new gatsby Application Version
       run: aws elasticbeanstalk update-enviroment —enviroment-name ${{ env.EB_ENVIROMENT_NAME }} —version-label "Ver-${{ github.sha }}"

     - name: Print Happy Massage for CD finish
       run: echo "CD Pipeline part Finished successfully!"  
